Check if pid is not found to be sure mysql is really shut.

diff --git a/mysql-backup b/mysql-backup
--- a/mysql-backup
+++ b/mysql-backup
@@ -466,13 +466,27 @@ function stop_mysqld_for_backup() {
     local mysql_cmd="${mysqladmin} \
         --defaults-extra-file="${mysqladmin_extra_file}" \
 	--socket=/tmp/${mysql_instance}.sock"
+    local pid=$(cat /tmp/${mysql_instance}.pid)
     for i in `seq 60`; do
 	sleep 1
+	log "Shutting down mysql: $mysql_cmd shut"
 	cmd "$mysql_cmd shut"
+	log "Testing if mysql is still alive: $mysql_cmd ping"
 	cmd "$mysql_cmd ping >/dev/null 2>&1"
         ec=$?
 	if test $ec -ne 0; then
-	    return
+	    log "mysql seems to be shut (ec=$ec), checking pid ($pid)..."
+	    for j in `seq 120`; do
+		cmd "ps -p $pid"
+		ec=$?
+		if test $ec -ne 0; then
+		    log "mysql pid $pid not found. This is good, backup can start."
+		    return
+		fi
+		log "mysql instance ${mysql_instance} is found for (pid: $pid)."
+		sleep 1
+	    done
+	    log "mysql instance ${mysql_instance} is still running (pid: $pid) after 120s. Something might be wrong."
 	fi
     done
     msg="ERROR Could not stop mysql instance ${mysql_instance}"
